package JDialog;

import JFrame.JFtelainicial;
import TableModel.TMAluno;
import classes.Aluno;
import gerente.GerenteAluno;
import javax.swing.JOptionPane;

public class JDAluno extends javax.swing.JDialog {
    
    private GerenteAluno alunos = new GerenteAluno();
    Aluno Teste = new Aluno();
    private boolean editando;
    TMAluno tmAluno;
    
    
    public JDAluno(java.awt.Frame parent, boolean modal, GerenteAluno alunos, TMAluno tmAluno) {
        super(parent, modal);
        initComponents();
        Habilitar_Campos(false);
        Limpar_Campos();
        this.alunos = alunos;
        this.editando = false;
        
        tmAluno = new TMAluno(alunos.getAlunos());
        
        AtualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnCadastroAluno = new javax.swing.JPanel();
        jlbCadastroAluno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jblMatricula = new javax.swing.JLabel();
        jblNome = new javax.swing.JLabel();
        jblGenero = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        jblIdade = new javax.swing.JLabel();
        jblAnoDeIngresso = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        txtAnoDeIngresso = new javax.swing.JTextField();
        JblCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbCadastroAluno.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jlbCadastroAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCadastroAluno.setText("Cadastro de Alunos");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo_32x32.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jblMatricula.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblMatricula.setText("Matricula:");

        jblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNome.setText("Nome:");

        jblGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblGenero.setText("Gênero:");

        jblIdade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblIdade.setText("Idade:");

        jblAnoDeIngresso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblAnoDeIngresso.setText("Ano de Ingresso: ");

        JblCPF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JblCPF.setText("CPF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(JblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jblGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(txtGenero)
                        .addGap(48, 48, 48))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(164, 164, 164))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtNome)
                                .addGap(41, 41, 41)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jblIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdade)
                                .addGap(39, 39, 39))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jblAnoDeIngresso, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoDeIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtMatricula))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdade)
                            .addComponent(jblIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4))
                    .addComponent(jblMatricula))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblAnoDeIngresso)
                            .addComponent(txtAnoDeIngresso)))
                    .addComponent(jblNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGenero)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblGenero)
                            .addComponent(JblCPF)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        grdAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Matricula", "Nome", "Sexo", "Idade", "Ano de Ingresso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grdAluno);

        javax.swing.GroupLayout jpnCadastroAlunoLayout = new javax.swing.GroupLayout(jpnCadastroAluno);
        jpnCadastroAluno.setLayout(jpnCadastroAlunoLayout);
        jpnCadastroAlunoLayout.setHorizontalGroup(
            jpnCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCadastroAlunoLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jlbCadastroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(255, 255, 255))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnCadastroAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jpnCadastroAlunoLayout.setVerticalGroup(
            jpnCadastroAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCadastroAlunoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbCadastroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnCadastroAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnCadastroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Habilitar_Campos(false);
        Limpar_Campos();
        this.editando = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.Habilitar_Campos(true);
        this.Limpar_Campos();
        this.editando = false;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Habilitar_Campos(false);
        Limpar_Campos();
        
        String cpf = JOptionPane.showInputDialog("Me informe o cpf do aluno para ser editado: ");
        Aluno A1 = alunos.Busca(Integer.parseInt(cpf));
        
        if (A1 != null){
            this.Teste = A1;
            editando = true;
            PreencherCamposAluno(A1);
            Habilitar_Campos_Edicao(true);

        }else{
            JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
            this.editando = false;
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Aluno A1 = new Aluno();
        
        if (editando != true){
            
            this.Coletar_Campos(A1);
            
            //Busca se existe algum aluno com o IDENTIFICADOR "CPF" se existir não será adicionado,caso contrario irá concluir a ação;
            Aluno find = alunos.Busca(A1.getCpf());
            if (find != null) {
                JOptionPane.showMessageDialog(this, "Erro: este aluno já existe.");
            }else{
                alunos.Adiciona(A1);
                this.Limpar_Campos();
                this.Habilitar_Campos(false);
                
                //Atualiza a JTable
               
                AtualizarTabela();
                
                //exibir uma menssagem de conclusão na tela
                JOptionPane.showMessageDialog(this, "Aluno adicionado com sucesso.");
                
               

            }
        }else{
            this.Coletar_Campos(A1);
            int index = this.alunos.getAlunos().indexOf(Teste);
            this.alunos.getAlunos().set(index, A1);
            this.Limpar_Campos();
            this.Habilitar_Campos(false);
            
            

            
            //Atualizando a JTable depois de ter feito a edição
            AtualizarTabela();
            
            //Mensagem de conclução de edição
            JOptionPane.showMessageDialog(this, "Aluno editado com sucesso.");
            
            
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.Habilitar_Campos(false);
        String cpf = JOptionPane.showInputDialog("Informe o CPF do aluno para ser removido.");
        Aluno A1 = this.alunos.Busca(Integer.parseInt(cpf));
        this.Habilitar_Campos(false);
        this.Limpar_Campos();
        this.editando = false;
        
        if (A1 == null) {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado.");
        }else{
            this.alunos.getAlunos().remove(A1);
            
           
            //Atualiza tabela
            AtualizarTabela();
            
            //Mensagem de aluno removido com sucesso
            JOptionPane.showMessageDialog(this, "Aluno removido com sucesso.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed
    
    private void AtualizarTabela(){
        tmAluno = new TMAluno(alunos.getAlunos());
        grdAluno.setModel(tmAluno);
    }
    
    private void Limpar_Campos(){
        txtCPF.setText("");
        txtMatricula.setText("");
        txtAnoDeIngresso.setText("");
        txtGenero.setText("");
        txtIdade.setText("");
        txtNome.setText("");
    }
    
    private void Habilitar_Campos_Edicao(boolean flag){
            txtMatricula.setEnabled(false);
            txtCPF.setEnabled(false);
            txtAnoDeIngresso.setEnabled(flag);
            txtIdade.setEnabled(flag);
            txtNome.setEnabled(flag);
            txtGenero.setEnabled(flag);
        }

    private void Habilitar_Campos(boolean flag){
        txtCPF.setEnabled(flag);
        txtMatricula.setEnabled(flag);
        txtAnoDeIngresso.setEnabled(flag);
        txtIdade.setEnabled(flag);
        txtNome.setEnabled(flag);
        txtGenero.setEnabled(flag);
    }
    
    private void PreencherCamposAluno(Aluno A1){
        txtCPF.setText(String.valueOf(A1.getCpf()));
        txtAnoDeIngresso.setText(String.valueOf(A1.getAno_ingresso()));
        txtGenero.setText(A1.getSexo());
        txtIdade.setText(String.valueOf(A1.getIdade()));
        txtMatricula.setText(String.valueOf(A1.getMatricula()));
        txtNome.setText(A1.getNome());
    }
    
    private void Coletar_Campos(Aluno A1){
        A1.setCpf(Integer.parseInt(txtCPF.getText()));
        A1.setAno_ingresso(Integer.parseInt(txtAnoDeIngresso.getText()));
        A1.setIdade(Integer.parseInt(txtIdade.getText()));
        A1.setMatricula(Integer.parseInt(txtMatricula.getText()));
        A1.setNome(txtNome.getText());
        A1.setSexo(txtGenero.getText());
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblCPF;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTable grdAluno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblAnoDeIngresso;
    private javax.swing.JLabel jblGenero;
    private javax.swing.JLabel jblIdade;
    private javax.swing.JLabel jblMatricula;
    private javax.swing.JLabel jblNome;
    private javax.swing.JLabel jlbCadastroAluno;
    private javax.swing.JPanel jpnCadastroAluno;
    private javax.swing.JTextField txtAnoDeIngresso;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
