package JDialog;

import JDialog.JDialog2.JDCadastroAluno;
import JDialog.JDialog2.JDCadastroProfessor;
import TableModel.TMAluno;
import TableModel.TMDisciplina;
import TableModel.TMProfessor;
import classes.Disciplina;
import classes.Professor;
import gerente.GerenteAluno;
import gerente.GerenteDisciplina;
import gerente.GerenteProfessor;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Otavio
 */
public class JDDisciplina extends javax.swing.JDialog {

   private boolean edicao;
   private GerenteProfessor professores;
   private GerenteAluno alunos;
   private GerenteDisciplina disciplina;
   private Professor ministrante;
   private TMAluno tmAluno;
   private TMProfessor tmProfessor;
   private TMDisciplina tmDisciplina;

   
   private GerenteAluno alunos_adicionar_disciplina;
         
    public JDDisciplina(java.awt.Frame parent, boolean modal, GerenteProfessor gerente_prof, GerenteDisciplina gerente_disciplina, GerenteAluno gerente_aluno, TMAluno tmAluno, TMProfessor tmProfessor, TMDisciplina tmDisciplina){
        
        super(parent, modal);
        initComponents();
        this.edicao = false;
        
        //Instanciando os Gerentes
        this.professores = new GerenteProfessor();
        this.alunos = new GerenteAluno();
        this.disciplina = new GerenteDisciplina();
              
        //
        this.professores = gerente_prof;
        this.alunos = gerente_aluno;
        this.disciplina = gerente_disciplina;
        
        //
        Atualiza_Disciplina();
        
        //
        
        this.Limpar_Campos();
        this.Habilitar_Campos(false);
        
        //
        
       btnProfessor.setEnabled(false);
       btnAluno.setEnabled(false);
       
       this.tmAluno = tmAluno;
       this.tmProfessor = tmProfessor;
       this.tmDisciplina = tmDisciplina;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jblNome = new javax.swing.JLabel();
        jblHorario = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtHorario = new javax.swing.JTextField();
        btnAluno = new javax.swing.JButton();
        btnProfessor = new javax.swing.JButton();
        jblSemestre = new javax.swing.JLabel();
        edtSemestre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        grdDisciplina = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbTitle.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jlbTitle.setText("Cadastro de Disciplina");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo_32x32.png"))); // NOI18N
        btnNovo.setText("Nova");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNome.setText("Nome:");

        jblHorario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblHorario.setText("Horário:");

        edtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtHorarioActionPerformed(evt);
            }
        });

        btnAluno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAluno.setText("Adicionar Alunos a Disciplina");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });

        btnProfessor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProfessor.setText("Adicionar Professor Ministrante");
        btnProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfessorActionPerformed(evt);
            }
        });

        jblSemestre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblSemestre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSemestre.setText("Semestre:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jblSemestre, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblNome)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblSemestre)
                    .addComponent(edtSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtHorario)
                            .addComponent(jblHorario))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        grdDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(grdDisciplina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTitle)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jlbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.Habilitar_Campos(true);
        this.Limpar_Campos();
        this.edicao = false;
        this.ministrante = new Professor();
        this.alunos_adicionar_disciplina = new GerenteAluno();
        
        btnProfessor.setEnabled(true);
        btnAluno.setEnabled(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.Limpar_Campos();
        this.Habilitar_Campos(false);
        this.edicao = false;
        
        // 
        
        btnProfessor.setEnabled(false);
        btnAluno.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        btnProfessor.setEnabled(false);
        btnAluno.setEnabled(false);
        
        Disciplina D1 = new Disciplina();
        
        String nome_disciplina_excluir = JOptionPane.showInputDialog("Me informe o nome da disciplina para ser excluida.");
        
        D1 = disciplina.Buscar_Disciplina(nome_disciplina_excluir);
        
        if (D1 == null) {
            JOptionPane.showMessageDialog(this, "Disciplina não encontrada.");
        }else{
            disciplina.Remover_Disciplina(nome_disciplina_excluir);
            Atualiza_Disciplina();
            JOptionPane.showMessageDialog(this, "Disciplina Removida com Sucesso.");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Disciplina D1 = new Disciplina();
        Disciplina verifica;
        
        
        if (edicao == false) {
            
           //Teste
           
           this.Coletar_Campos(D1);
           verifica = this.disciplina.Buscar_Disciplina(D1.getNome());
            if (verifica != null) {
                JOptionPane.showMessageDialog(this, "Erro: Já existe uma disciplina com este nome.");
            }else{
                
                this.disciplina.Adicionar_Disciplina(D1);
                Atualiza_Disciplina();
                JOptionPane.showMessageDialog(this, "Disciplina cadastrada com sucesso.");
                this.Limpar_Campos();
                this.Habilitar_Campos(false);
                btnProfessor.setEnabled(false);
                btnAluno.setEnabled(false);
            }
        }else{
            
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    //Tela Cadastrar professor, TELA CADASTRAR ALUNO LOGO ABAIXO.
    
    private void btnProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfessorActionPerformed
        this.ministrante = new Professor();
        JDCadastroProfessor tela_professor = new JDCadastroProfessor(new Frame(), true, professores, tmProfessor);
        tela_professor.setVisible(true);
        this.ministrante = tela_professor.getMinistrante();
        
    }//GEN-LAST:event_btnProfessorActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        
        btnProfessor.setEnabled(false);
        btnAluno.setEnabled(false);
        
    }//GEN-LAST:event_btnEditarActionPerformed
    
    //Tela do cadastrar Aluno, TELA CADASTRAR PROFESSOR LOGO ACIMA.
    
    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        JDCadastroAluno tela_aluno = new JDCadastroAluno(new Frame() , true, alunos, tmAluno);
        tela_aluno.setVisible(true);
        this.alunos_adicionar_disciplina = tela_aluno.getAlunos_adicionados();
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void edtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtHorarioActionPerformed

    public void Limpar_Campos(){
        edtNome.setText("");
        edtHorario.setText("");
        edtSemestre.setText("");
    }
    
    public void Habilitar_Campos(boolean flag){
      edtNome.setEnabled(flag);
      edtHorario.setEnabled(flag);
      edtSemestre.setEnabled(flag);
    }
    
    public void PreencherCamposAluno(Disciplina A1){
        
    }
    
    private void Coletar_Campos(Disciplina D1){
        D1.setNome(edtNome.getText());
        D1.setSemestre(Integer.parseInt(edtSemestre.getText()));
        D1.setHora(edtHorario.getText());
        
        if (ministrante != null){
            D1.setMinistrante(ministrante);
        }
        
        if (this.alunos_adicionar_disciplina != null){
            D1.setAlunos(alunos_adicionar_disciplina);
        }
    }
    
    public void Atualiza_Disciplina(){
        tmDisciplina = new TMDisciplina(disciplina.getDisciplinas());
        grdDisciplina.setModel(tmDisciplina);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnProfessor;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtSemestre;
    private javax.swing.JTable grdDisciplina;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblHorario;
    private javax.swing.JLabel jblNome;
    private javax.swing.JLabel jblSemestre;
    private javax.swing.JLabel jlbTitle;
    // End of variables declaration//GEN-END:variables
}
