package com.mycompany.atividade01.gui;

import classes.GerenciadorMusica;
import classes.Musica;
import javax.swing.JOptionPane;

public class JFCadMusica extends javax.swing.JFrame {
    
    GerenciadorMusica gerenciador = new GerenciadorMusica();
    boolean editando = false;
    Integer Index_Escolhido;
    
    public JFCadMusica() {
        initComponents();
        this.Limpar_Campos();
        this.Habilitar_Campos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrincipal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        edtID = new javax.swing.JTextField();
        lblArtista = new javax.swing.JLabel();
        edtArtista = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        edtPreco = new javax.swing.JTextField();
        lblDuracao = new javax.swing.JLabel();
        edtDuracao = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        edtTitulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtListagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrincipal.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lblPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrincipal.setText("Cadastro Música");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/novo_32x32.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNovo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit3_32x32.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_32x32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del_32x32.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_32x32.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        lblID.setText("ID:");

        edtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIDActionPerformed(evt);
            }
        });

        lblArtista.setText("Artista:");

        edtArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtArtistaActionPerformed(evt);
            }
        });

        lblPreco.setText("Preco:");

        edtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPrecoActionPerformed(evt);
            }
        });

        lblDuracao.setText("Duração:");

        edtDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDuracaoActionPerformed(evt);
            }
        });

        lblTitulo.setText("Titulo:");

        edtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtTitulo)
                    .addComponent(edtID)
                    .addComponent(edtArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(edtPreco))
                .addGap(326, 326, 326))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtID)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtArtista)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblArtista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edtPreco))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(edtDuracao))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(edtTitulo))
                .addContainerGap())
        );

        edtListagem.setColumns(20);
        edtListagem.setRows(5);
        jScrollPane1.setViewportView(edtListagem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.Habilitar_Campos(false);
        this.Limpar_Campos();
        String ID_Escolhido = JOptionPane.showInputDialog("Me informe o ID da musica." , "");
        Musica musica_a_ser_editada = this.gerenciador.buscarMusica(Integer.parseInt(ID_Escolhido));
        
        if (musica_a_ser_editada != null){
            this.editando = true;
            this.Habilitar_Campos_Edicao(true);
            this.Preencher_Campos_Edt(musica_a_ser_editada);
            this.Index_Escolhido = gerenciador.getMusicas().indexOf(musica_a_ser_editada);
            JOptionPane.showMessageDialog(this, Index_Escolhido);
        }else{
            JOptionPane.showMessageDialog(this, "ID Invalido.");
            this.Limpar_Campos();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.Limpar_Campos();
        this.Habilitar_Campos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.Limpar_Campos();
        this.Habilitar_Campos(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        String ID_Musica = JOptionPane.showInputDialog("Informe o ID da Musica.");
        Musica M1 = gerenciador.buscarMusica(Integer.parseInt(ID_Musica));
        
        if (M1 != null){
            int index = gerenciador.getMusicas().indexOf(M1);
            this.gerenciador.getMusicas().remove(index);
            JOptionPane.showMessageDialog(this, "Musica deletada com sucesso.");
            edtListagem.setText(gerenciador.toString());
        }else{
            JOptionPane.showMessageDialog(this, "Musica não encontrada.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        if(editando){
          Musica M1 = Preencher_Campos_Musica();
          gerenciador.getMusicas().set(Index_Escolhido, M1);
          edtListagem.setText(gerenciador.toString());
          this.Limpar_Campos();
          this.Habilitar_Campos(false);
          JOptionPane.showMessageDialog(this, "Musica Atualizada com Sucesso");
          this.editando = false;
        }else{
            Musica M1 = Preencher_Campos_Musica();
            
            if(gerenciador.buscarMusica(M1.getID()) == null){
                gerenciador.adicionarMusica(M1);
                edtListagem.setText(gerenciador.toString());
                this.Habilitar_Campos(false);
                this.Limpar_Campos();
            }else{
                JOptionPane.showMessageDialog(this, "Já existe uma musica com este ID.");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void edtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIDActionPerformed

    private void edtArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtArtistaActionPerformed

    private void edtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPrecoActionPerformed

    private void edtDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDuracaoActionPerformed

    private void edtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTituloActionPerformed

    public void Preencher_Campos_Edt(Musica musica){
        edtID.setText(String.valueOf(musica.getID()));
        edtArtista.setText(musica.getArtista());
        edtTitulo.setText(musica.getTitulo());
        edtDuracao.setText(String.valueOf(musica.getDuracao()));
        edtPreco.setText(String.valueOf(musica.getPreco()));
    }
    
    public Musica Preencher_Campos_Musica(){
        Musica M1 = new Musica();
        
        M1.setId(Integer.parseInt(edtID.getText()));
        M1.setArtista(edtArtista.getText());
        M1.setTitulo(edtTitulo.getText());
        M1.setDuracao(Integer.parseInt(edtDuracao.getText()));
        M1.setPreco(Double.parseDouble(edtPreco.getText()));
        
        return M1;
    }
    
    public void Habilitar_Campos_Edicao(boolean flag){
        edtID.setEnabled(false);
        edtArtista.setEnabled(flag);
        edtTitulo.setEnabled(flag);
        edtPreco.setEnabled(flag);
        edtDuracao.setEnabled(flag);
    }
    
    public void Habilitar_Campos(boolean flag){
        edtID.setEnabled(flag);
        edtArtista.setEnabled(flag);
        edtTitulo.setEnabled(flag);
        edtPreco.setEnabled(flag);
        edtDuracao.setEnabled(flag);
    }
    
    public void Limpar_Campos(){
        edtID.setText("");
        edtArtista.setText("");
        edtTitulo.setText("");
        edtPreco.setText("");
        edtDuracao.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtArtista;
    private javax.swing.JTextField edtDuracao;
    private javax.swing.JTextField edtID;
    private javax.swing.JTextArea edtListagem;
    private javax.swing.JTextField edtPreco;
    private javax.swing.JTextField edtTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblPrincipal;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
